version: "3.8"

services:
  db:
    image: postgres:14.4
    container_name: world-traveller
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=countries_db
      - POSTGRES_PASSWORD=countries
    ports:
      - 5433:5432
